const kurtaKurtiData = [
  {
    name: "Women Cotton A-line Kurta",
    description:
      "Comfortable and stylish A-line kurta made from pure cotton, ideal for casual wear and daily use.",
    price: 1299,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/ethnic-set/1/c/4/xxl-r84-711-shoppinghub-original-imagr7z5ehyygujc.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/u/3/e/xxl-white-kurta-shourya-fashion-original-imagsy5zgkyg7vwf.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/w/l/r/xxl-white-kurta-shourya-fashion-original-imagsy5zcv3zdz2z.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Cotton",
      Type: "A-line Kurta",
      Pattern: "Solid",
      Color: "White",
      Occasion: "Casual, Daily Wear",
      "Fabric care": "Hand Wash",
    },
    stockQuantity: 20,
  },
  {
    name: "Women Rayon Straight Kurti",
    description:
      "Elegant and comfortable straight kurti made from soft rayon fabric, perfect for office wear and semi-formal events.",
    price: 1499,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/f/t/f/m-rs-95-kround-yellow-navyblue-m-rockshok-original-imaggbqzjdzvtgtu.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/c/o/q/m-rs-95-kround-yellow-navyblue-m-rockshok-original-imaggbqzbdd4hzw2.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/s/1/1/m-rs-95-kround-yellow-navyblue-m-rockshok-original-imaggbqzzv2mudgr.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/v/3/1/m-rs-95-kround-yellow-navyblue-m-rockshok-original-imaggbqzmpb5ezht.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/w/k/1/m-rs-95-kround-yellow-navyblue-m-rockshok-original-imaggbqzfhjppyhe.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/w/k/1/m-rs-95-kround-yellow-navyblue-m-rockshok-original-imaggbqzfhjppyhe.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Rayon",
      Type: "Straight Kurti",
      Pattern: "Printed",
      Color: "Blue, Yellow",
      Occasion: "Office Wear, Semi-formal",
      "Fabric care": "Machine Wash",
    },
    stockQuantity: 18,
  },
  {
    name: "Women Silk Anarkali Kurti",
    description:
      "Graceful silk anarkali kurti with intricate embroidery, suitable for festive occasions and cultural gatherings.",
    price: 2799,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/4/m/m/4xl-pink-silk-printed-gown-krina-enterprises-original-imagtyh8supecz4x.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/4/m/m/4xl-pink-silk-printed-gown-krina-enterprises-original-imagtyh8supecz4x.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/4/m/m/4xl-pink-silk-printed-gown-krina-enterprises-original-imagtyh8supecz4x.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/shopsy-gown/5/y/w/m-full-sleeve-stitched-pankhudi-glv-fashion-original-imagsw5kp59qwppx.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Silk",
      Type: "Anarkali Kurti",
      Pattern: "Embroidered",
      Color: "Pink, Gold",
      Occasion: "Festive, Cultural",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 15,
  },
  {
    name: "Women Linen Kurti with Palazzo",
    description:
      "Stylish linen kurti paired with matching palazzo pants, perfect for summer outings and casual gatherings.",
    price: 1999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/salwar-kurta-dupatta/d/x/j/xl-new-kurta-palazzo-and-dupatta-set-bkapparels-original-imahyr5h6hwnmbj9.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/salwar-kurta-dupatta/h/u/l/xxl-cotton-suit-3pcs-shefair-original-imahyyz9zhwgavmt.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/salwar-kurta-dupatta/h/u/l/xxl-cotton-suit-3pcs-shefair-original-imahyyz9zhwgavmt.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/salwar-kurta-dupatta/d/v/5/xl-new-kurta-palazzo-and-dupatta-set-bkapparels-original-imahyr5hbwbhh4bg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/salwar-kurta-dupatta/y/c/x/xxl-cotton-suit-3pcs-shefair-original-imahyyz9taejmuzq.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Linen",
      Type: "Kurti with Palazzo",
      Pattern: "Striped",
      Color: "Green, White",
      Occasion: "Summer Outings, Casual",
      "Fabric care": "Hand Wash",
    },
    stockQuantity: 22,
  },
  {
    name: "Women Chanderi Silk Kurti",
    description:
      "Chic Chanderi silk kurti with traditional motifs and golden zari work, ideal for formal events and evening parties.",
    price: 3499,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/ethnic-set/n/h/r/l-chanderi-dishwa-fashion-original-imahfvc8rphaghsq.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/ethnic-set/v/a/y/l-chanderi-dishwa-fashion-original-imahfvc8rgc5bmdr.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/ethnic-set/n/y/i/l-chanderi-dishwa-fashion-original-imahfvc8vtzwg3wg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/ethnic-set/v/a/y/l-chanderi-dishwa-fashion-original-imahfvc8rgc5bmdr.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Chanderi Silk",
      Type: "Kurti",
      Pattern: "Zari Work",
      Color: "Beige, Gold",
      Occasion: "Formal, Evening",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 16,
  },
  {
    name: "Women Georgette Kurta",
    description:
      "Flowy georgette kurta with minimalistic design, perfect for modern fashionistas and chic daytime events.",
    price: 1699,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/l/7/w/m-midindigoking-made-in-desi-original-imaghmy5ecpzg7gz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/l/7/w/m-midindigoking-made-in-desi-original-imaghmy5ecpzg7gz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/l/7/w/m-midindigoking-made-in-desi-original-imaghmy5ecpzg7gz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/l/7/w/m-midindigoking-made-in-desi-original-imaghmy5ecpzg7gz.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Georgette",
      Type: "Kurta",
      Pattern: "Plain",
      Color: "Navy Blue",
      Occasion: "Daytime Events, Modern",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 20,
  },
  {
    name: "Women Printed Cotton Kurti",
    description:
      "Comfortable printed cotton kurti with vibrant patterns, ideal for casual outings and everyday wear.",
    price: 1099,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/q/y/w/s-1068-ekeswara-original-imagw3tfhhrmxfqh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/q/y/w/s-1068-ekeswara-original-imagw3tfhhrmxfqh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/l/q/r/s-1068-ekeswara-original-imagw3tf8a8bcprg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/m/i/c/s-1068-ekeswara-original-imagw3tfdrrhfb8p.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/m/i/c/s-1068-ekeswara-original-imagw3tfdrrhfb8p.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Cotton",
      Type: "Printed Kurti",
      Pattern: "Floral Print",
      Color: "Red, White",
      Occasion: "Casual, Everyday",
      "Fabric care": "Hand Wash",
    },
    stockQuantity: 25,
  },
  {
    name: "Women Khadi Kurti",
    description:
      "Handcrafted khadi kurti with traditional weaving, perfect for eco-friendly fashion enthusiasts and cultural events.",
    price: 1899,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/l/a/p/s-kurti-printed-kidporium-original-imahffry9cyyxv8a.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/b/2/w/l-kurti-new-kidporium-original-imahyhe8y825gcyw.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/h/7/k/l-kurti-new-kidporium-original-imahyhe882bu3uug.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Khadi",
      Type: "Handloom Kurti",
      Pattern: "Woven",
      Color: "Off-White",
      Occasion: "Cultural, Eco-friendly",
      "Fabric care": "Hand Wash",
    },
    stockQuantity: 18,
  },
  {
    name: "Women Crepe Kurta",
    description:
      "Stylish crepe kurta with contemporary design, suitable for formal events and evening gatherings.",
    price: 2399,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/n/m/f/xl-fll-black-xl-jayshree-original-imaguazgqpshtdya.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/s/n/e/xl-fll-black-xl-jayshree-original-imaguazgyhnhrbyh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/s/n/e/xl-fll-black-xl-jayshree-original-imaguazgyhnhrbyh.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Crepe",
      Type: "Kurta",
      Pattern: "Abstract Print",
      Color: "Black, Pink",
      Occasion: "Formal, Evening",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 14,
  },
  {
    name: "Women Embellished Kurti",
    description:
      "Elegant embellished kurti with intricate beadwork and sequin embellishments, ideal for festive celebrations and special occasions.",
    price: 2999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/l0h1g280/kurta/d/p/p/3xl-dkr456c-dress-metro-fashion-original-imagc9yh6ghqxgqs.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/l0h1g280/kurta/j/l/e/3xl-dkr456c-dress-metro-fashion-original-imagc9yhfn5pvcbq.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/l0h1g280/kurta/q/d/m/3xl-dkr456c-dress-metro-fashion-original-imagc9yhqgpzchyj.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/l0h1g280/kurta/a/v/w/3xl-dkr456c-dress-metro-fashion-original-imagc9yhfchee3tf.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Chiffon",
      Type: "Embellished Kurti",
      Pattern: "Beaded",
      Color: "Blue, Silver",
      Occasion: "Festive, Special Occasions",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 12,
  },
  {
    name: "Women Block Print Cotton Kurta",
    description:
      "Handcrafted block print cotton kurta with traditional motifs, perfect for casual outings and cultural events.",
    price: 1599,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/kgtqhe80-0/kurta/y/k/t/m-164-186-m-round-neck-straight-crepe-combo-pack-of-2-kurta-for-original-imafwz7fwjqnbdjz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/kflftzk0-0/kurta/n/h/b/l-164-l-fancy-straight-digital-printed-crepe-kurti-for-women-original-imafwyu2dgpgjvhg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/kd94uq80-0/kurti/b/d/2/l-184-l-new-latest-designer-trendy-best-price-american-crepe-original-imafu7bjna7gucxe.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/e/8/5/xl-combo-printed-kurti-casual-party-wear-latest-pack-of-2-kurta-original-imafu7b8ybddgrsq.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/e/8/5/xl-combo-printed-kurti-casual-party-wear-latest-pack-of-2-kurta-original-imafu7b8ybddgrsq.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/e/8/5/xl-combo-printed-kurti-casual-party-wear-latest-pack-of-2-kurta-original-imafu7b8ybddgrsq.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/e/8/5/xl-combo-printed-kurti-casual-party-wear-latest-pack-of-2-kurta-original-imafu7b8ybddgrsq.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Cotton",
      Type: "Block Print Kurta",
      Pattern: "Block Print",
      Color: "Indigo, White",
      Occasion: "Casual, Cultural",
      "Fabric care": "Hand Wash",
    },
    stockQuantity: 18,
  },
  {
    name: "Women Floral Embroidered Kurti",
    description:
      "Charming floral embroidered kurti with delicate thread work, ideal for daytime parties and festive gatherings.",
    price: 1899,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/kl5hh8w0/kurta/9/c/l/xxl-kurticombo-42-48-49-j-2-fashion-original-imagyc27amavfxk9.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/kl5hh8w0/kurta/9/c/l/xxl-kurticombo-42-48-49-j-2-fashion-original-imagyc27amavfxk9.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Georgette",
      Type: "Embroidered Kurti",
      Pattern: "Floral Embroidery",
      Color: "Pink, Green",
      Occasion: "Daytime Parties, Festive",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 16,
  },
  {
    name: "Women Printed Rayon Kurta Set",
    description:
      "Stylish printed rayon kurta set with matching palazzo pants, perfect for summer outings and casual wear.",
    price: 2199,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/salwar-kurta-dupatta/s/u/b/m-slk-109-blue-subh-laxmi-original-imagwwhhyyb34zem.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/salwar-kurta-dupatta/s/u/b/m-slk-109-blue-subh-laxmi-original-imagwwhhyyb34zem.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Rayon",
      Type: "Kurta with Palazzo",
      Pattern: "Printed",
      Color: "Blue, Yellow",
      Occasion: "Summer Outings, Casual",
      "Fabric care": "Hand Wash",
    },
    stockQuantity: 20,
  },
  {
    name: "Women Angrakha Style Kurta",
    description:
      "Traditional Angrakha style kurta with tie-up detailing and ethnic charm, suitable for festive occasions and cultural gatherings.",
    price: 2499,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/z/w/r/xl-inst2357-indyes-original-imagqcqahnjwtmfk.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/z/w/r/xl-inst2357-indyes-original-imagqcqahnjwtmfk.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/z/w/r/xl-inst2357-indyes-original-imagqcqahnjwtmfk.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/b/z/i/xl-inst2357-indyes-original-imagqcqa76qyc7kn.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/j/r/j/xl-inst2357-indyes-original-imagqcqaffq7rggy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/j/r/j/xl-inst2357-indyes-original-imagqcqaffq7rggy.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Cotton",
      Type: "Angrakha Style Kurta",
      Pattern: "Solid",
      Color: "Red",
      Occasion: "Festive, Cultural",
      "Fabric care": "Hand Wash",
    },
    stockQuantity: 15,
  },
  {
    name: "Women Silk Tunic",
    description:
      "Elegant silk tunic with contemporary design, perfect for formal events and evening gatherings.",
    price: 2799,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/top/8/6/w/xxl-1-pc-041black-panghat-collection-original-imagqxyav2n6gjx9.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/top/8/6/w/xxl-1-pc-041black-panghat-collection-original-imagqxyav2n6gjx9.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/top/8/6/w/xxl-1-pc-041black-panghat-collection-original-imagqxyav2n6gjx9.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Silk",
      Type: "Tunic",
      Pattern: "Solid",
      Color: "Black",
      Occasion: "Formal, Evening",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 14,
  },
  {
    name: "Women Embroidered Chanderi Kurta",
    description:
      "Exquisite embroidered Chanderi kurta with traditional motifs and golden zari work, ideal for festive celebrations.",
    price: 2999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/9/l/c/m-sk-14-green-bandej-kurta-physil-original-imahfps44xpg5vma.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/h/5/g/m-sk-14-green-bandej-kurta-physil-original-imahfps4trydhzu3.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/h/5/g/m-sk-14-green-bandej-kurta-physil-original-imahfps4trydhzu3.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/h/5/g/m-sk-14-green-bandej-kurta-physil-original-imahfps4trydhzu3.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/h/5/g/m-sk-14-green-bandej-kurta-physil-original-imahfps4trydhzu3.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/h/5/g/m-sk-14-green-bandej-kurta-physil-original-imahfps4trydhzu3.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/h/5/g/m-sk-14-green-bandej-kurta-physil-original-imahfps4trydhzu3.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Chanderi",
      Type: "Embroidered Kurta",
      Pattern: "Embroidered",
      Color: "Green, Gold",
      Occasion: "Festive, Special Occasions",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 12,
  },
  {
    name: "Women Linen Straight Kurta",
    description:
      "Stylish linen straight kurta with minimalist design, perfect for everyday wear and casual outings.",
    price: 1799,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/krayqa80/kurta/y/f/m/xxl-kr501a-metro-fashion-original-imag54exsm2bt5xg.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/krayqa80/kurta/u/b/o/xxl-kr501a-metro-fashion-original-imag54exknnfw95y.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/krayqa80/kurta/u/b/o/xxl-kr501a-metro-fashion-original-imag54exknnfw95y.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/krayqa80/kurta/u/b/o/xxl-kr501a-metro-fashion-original-imag54exknnfw95y.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/krayqa80/kurta/u/b/o/xxl-kr501a-metro-fashion-original-imag54exknnfw95y.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Linen",
      Type: "Straight Kurta",
      Pattern: "Solid",
      Color: "Beige",
      Occasion: "Casual, Everyday",
      "Fabric care": "Hand Wash",
    },
    stockQuantity: 22,
  },
  {
    name: "Women Printed Cotton Kurta",
    description:
      "Comfortable printed cotton kurta with vibrant patterns, ideal for casual outings and daily wear.",
    price: 1399,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/m/p/g/l-67591-sgle-bandi-foil-lkurti-pslyrse-buy-that-trendz-original-imagjnpgqvkcrzne.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/q/o/w/l-67591-sgle-bandi-foil-lkurti-pslyrse-buy-that-trendz-original-imagjnpgchkjfw3k.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Cotton",
      Type: "Printed Kurta",
      Pattern: "Abstract Print",
      Color: "Pink, White",
      Occasion: "Casual, Daily Wear",
      "Fabric care": "Hand Wash",
    },
    stockQuantity: 25,
  },
  {
    name: "Women Embellished Anarkali Kurti",
    description:
      "Beautiful embellished anarkali kurti with intricate beadwork and sequin embellishments, perfect for weddings and festive occasions.",
    price: 3499,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/j/v/f/m-maya-1011-mayaakshay-original-imagsjuh6fmzz7j7.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/kurta/j/v/f/m-maya-1011-mayaakshay-original-imagsjuh6fmzz7j7.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Georgette",
      Type: "Embellished Anarkali Kurti",
      Pattern: "Beaded",
      Color: "Blue, Silver",
      Occasion: "Wedding, Festive",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 12,
  },
  {
    name: "Women Banarasi Silk Kurti",
    description:
      "Luxurious Banarasi silk kurti with traditional weaving and golden zari work, ideal for formal events and cultural gatherings.",
    price: 3899,
    images: [
      "https://rukminim2.flixcart.com/image/180/180/xif0q/sari/c/6/w/free-06-pubg-06-ugam-fashion-unstitched-original-imagh9f8mzzgnwqr.jpeg?q=50",
      "https://rukminim2.flixcart.com/image/180/180/xif0q/sari/c/6/w/free-06-pubg-06-ugam-fashion-unstitched-original-imagh9f8mzzgnwqr.jpeg?q=50",
      "https://rukminim2.flixcart.com/image/180/180/xif0q/sari/c/6/w/free-06-pubg-06-ugam-fashion-unstitched-original-imagh9f8mzzgnwqr.jpeg?q=50",
      "https://rukminim2.flixcart.com/image/180/180/xif0q/sari/c/6/w/free-06-pubg-06-ugam-fashion-unstitched-original-imagh9f8mzzgnwqr.jpeg?q=50",
      "https://rukminim2.flixcart.com/image/180/180/xif0q/sari/c/6/w/free-06-pubg-06-ugam-fashion-unstitched-original-imagh9f8mzzgnwqr.jpeg?q=50",
      "https://rukminim2.flixcart.com/image/180/180/xif0q/sari/c/6/w/free-06-pubg-06-ugam-fashion-unstitched-original-imagh9f8mzzgnwqr.jpeg?q=50",
    ],
    attributes: {
      Fabric: "Banarasi Silk",
      Type: "Kurti",
      Pattern: "Zari Work",
      Color: "Red, Gold",
      Occasion: "Formal, Cultural",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 10,
  },
  {
    name: "Women Mirror Work Lehenga Choli",
    description:
      "Stunning mirror work lehenga choli with intricate designs, perfect for weddings and festive occasions.",
    price: 15999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/0/k/i/free-half-sleeve-pochampalli-pattu-fabcartz-original-imaggvyjfgavuzyf.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/0/k/i/free-half-sleeve-pochampalli-pattu-fabcartz-original-imaggvyjfgavuzyf.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/z/n/i/free-half-sleeve-pochampalli-pattu-fabcartz-original-imagpts8zmxcb67h.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/z/n/i/free-half-sleeve-pochampalli-pattu-fabcartz-original-imagpts8zmxcb67h.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/z/n/i/free-half-sleeve-pochampalli-pattu-fabcartz-original-imagpts8zmxcb67h.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Georgette",
      Type: "Lehenga Choli",
      Pattern: "Mirror Work",
      Color: "Pink, Silver",
      Occasion: "Wedding, Festive",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 9,
  },
  {
    name: "Women Kanjeevaram Silk Lehenga Choli",
    description:
      "Luxurious Kanjeevaram silk lehenga choli with traditional motifs, ideal for weddings and cultural events.",
    price: 18999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/shopsy-lehenga-choli/g/q/2/free-full-sleeve-semi-stitched-ms-239-lehenga-choli-kinjal-original-imagsjj9zztqzfet.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/shopsy-lehenga-choli/g/q/2/free-full-sleeve-semi-stitched-ms-239-lehenga-choli-kinjal-original-imagsjj9zztqzfet.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Kanjeevaram Silk",
      Type: "Lehenga Choli",
      Pattern: "Woven",
      Color: "Purple, Gold",
      Occasion: "Wedding, Cultural",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 7,
  },
  {
    name: "Women Jacquard Lehenga Choli",
    description:
      "Elegant jacquard lehenga choli with intricate weaving, perfect for formal events and festive celebrations.",
    price: 13999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/i/b/q/free-half-sleeve-ak3-a-chakali-gajari-bhakti-swami-studio-original-imagugnkgccnyyw9.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/t/b/s/free-half-sleeve-ak3-a-chakali-gajari-anadi-swami-studio-original-imagtnwxb4rgpqyw.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/t/b/s/free-half-sleeve-ak3-a-chakali-gajari-anadi-swami-studio-original-imagtnwxb4rgpqyw.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/t/b/s/free-half-sleeve-ak3-a-chakali-gajari-anadi-swami-studio-original-imagtnwxb4rgpqyw.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/t/b/s/free-half-sleeve-ak3-a-chakali-gajari-anadi-swami-studio-original-imagtnwxb4rgpqyw.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Jacquard",
      Type: "Lehenga Choli",
      Pattern: "Woven",
      Color: "Green, Gold",
      Occasion: "Formal, Festive",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 10,
  },
  {
    name: "Women Resham Work Lehenga Choli",
    description:
      "Beautiful resham work lehenga choli with delicate thread embroidery, ideal for weddings and grand occasions.",
    price: 17999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/p/z/s/free-half-sleeve-patola-semi-stitched-fabcartz-original-imagrb9dnwkhcmyb.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/w/7/c/free-half-sleeve-patola-semi-stitched-fabcartz-original-imagrb9dhnbukpkz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/w/7/c/free-half-sleeve-patola-semi-stitched-fabcartz-original-imagrb9dhnbukpkz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/q/h/e/free-half-sleeve-patola-semi-stitched-fabcartz-original-imagrb9d77wkthah.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/q/h/e/free-half-sleeve-patola-semi-stitched-fabcartz-original-imagrb9d77wkthah.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Silk",
      Type: "Lehenga Choli",
      Pattern: "Embroidered",
      Color: "Red, Gold",
      Occasion: "Wedding, Grand Occasions",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 8,
  },
  {
    name: "Women Printed Crepe Lehenga Choli",
    description:
      "Stylish printed crepe lehenga choli with modern designs, perfect for casual outings and parties.",
    price: 9999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/c/k/8/free-short-sleeve-big-pallavi-l-orange-print-trivety-original-imagqype6tgscrdb.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/c/k/8/free-short-sleeve-big-pallavi-l-orange-print-trivety-original-imagqype6tgscrdb.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Crepe",
      Type: "Lehenga Choli",
      Pattern: "Printed",
      Color: "Blue, White",
      Occasion: "Casual, Party",
      "Fabric care": "Hand Wash",
    },
    stockQuantity: 12,
  },
  {
    name: "Women Net Embroidered Lehenga Choli",
    description:
      "Exquisite net embroidered lehenga choli with intricate designs, ideal for weddings and special occasions.",
    price: 14999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/kk2wl8w0/lehenga-choli/n/n/n/free-sleeveless-designer-big-green-gold-lehenga-choli-vega-1-st-original-imafzg3fqgnycged.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/kk76wsw0/lehenga-choli/1/p/0/free-sleeveless-designer-big-green-gold-lehenga-choli-vega-1-st-original-imafzhdfuhusyukd.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/kk76wsw0/lehenga-choli/1/p/0/free-sleeveless-designer-big-green-gold-lehenga-choli-vega-1-st-original-imafzhdfuhusyukd.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Net",
      Type: "Lehenga Choli",
      Pattern: "Embroidered",
      Color: "Peach, Gold",
      Occasion: "Wedding, Special Occasions",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 10,
  },
  {
    name: "Women Satin Lehenga Choli",
    description:
      "Elegant satin lehenga choli with sleek design and luxurious feel, perfect for formal events and evening parties.",
    price: 12999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/0/1/d/free-half-sleeve-chaniya-choli-freydis-original-imahy8r8zvn7hggd.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/0/1/d/free-half-sleeve-chaniya-choli-freydis-original-imahy8r8zvn7hggd.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/0/1/d/free-half-sleeve-chaniya-choli-freydis-original-imahy8r8zvn7hggd.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/0/1/d/free-half-sleeve-chaniya-choli-freydis-original-imahy8r8zvn7hggd.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/0/1/d/free-half-sleeve-chaniya-choli-freydis-original-imahy8r8zvn7hggd.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Satin",
      Type: "Lehenga Choli",
      Pattern: "Solid",
      Color: "Navy Blue, Silver",
      Occasion: "Formal, Evening",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 14,
  },
  {
    name: "Women Gota Patti Work Lehenga Choli",
    description:
      "Traditional gota patti work lehenga choli with intricate details, ideal for festive celebrations and cultural events.",
    price: 15999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/y/i/h/free-3-4-sleeve-1283-atsevam-original-imaghr2ykqhmmfuy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/y/i/h/free-3-4-sleeve-1283-atsevam-original-imaghr2ykqhmmfuy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/y/i/h/free-3-4-sleeve-1283-atsevam-original-imaghr2ykqhmmfuy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/y/i/h/free-3-4-sleeve-1283-atsevam-original-imaghr2ykqhmmfuy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/y/i/h/free-3-4-sleeve-1283-atsevam-original-imaghr2ykqhmmfuy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/y/i/h/free-3-4-sleeve-1283-atsevam-original-imaghr2ykqhmmfuy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/y/i/h/free-3-4-sleeve-1283-atsevam-original-imaghr2ykqhmmfuy.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Silk",
      Type: "Lehenga Choli",
      Pattern: "Gota Patti",
      Color: "Yellow, Gold",
      Occasion: "Festive, Cultural",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 11,
  },
  {
    name: "Women Sequin Work Lehenga Choli",
    description:
      "Glamorous sequin work lehenga choli with sparkling design, perfect for weddings and evening parties.",
    price: 18999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/a/a/b/free-pochampalli-pattu-fabcartz-unstitched-original-imagkyhqu7yc2z4v.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/a/a/b/free-pochampalli-pattu-fabcartz-unstitched-original-imagkyhqu7yc2z4v.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/a/a/b/free-pochampalli-pattu-fabcartz-unstitched-original-imagkyhqu7yc2z4v.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/a/a/b/free-pochampalli-pattu-fabcartz-unstitched-original-imagkyhqu7yc2z4v.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Net",
      Type: "Lehenga Choli",
      Pattern: "Sequined",
      Color: "Silver, Pink",
      Occasion: "Wedding, Party",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 9,
  },
  {
    name: "Women Lace Lehenga Choli",
    description:
      "Elegant lace lehenga choli with delicate lace work, ideal for weddings and special occasions.",
    price: 16999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/p/j/k/free-half-sleeve-108-pink-women-lehenga-choli-latest-tasrika-original-imahfgvv3sufnahy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/p/j/k/free-half-sleeve-108-pink-women-lehenga-choli-latest-tasrika-original-imahfgvv3sufnahy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/g/u/x/free-half-sleeve-108-pink-women-lehenga-choli-latest-tasrika-original-imagzzg8hx5ggvhd.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/lehenga-choli/g/u/x/free-half-sleeve-108-pink-women-lehenga-choli-latest-tasrika-original-imagzzg8hx5ggvhd.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Lace",
      Type: "Lehenga Choli",
      Pattern: "Lace Work",
      Color: "White, Gold",
      Occasion: "Wedding, Special Occasions",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 10,
  },
];

export default kurtaKurtiData