const sareeData = [
  {
    name: "Traditional Silk Saree",
    description:
      "Elegant silk saree with intricate zari work, perfect for weddings and special occasions.",
    price: 4999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/z/n/h/free-677-peach-maroon-designer-bollywood-fashion-style-saree-for-original-imahfb9bqfnwmugy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/z/n/h/free-677-peach-maroon-designer-bollywood-fashion-style-saree-for-original-imahfb9bqfnwmugy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/z/n/h/free-677-peach-maroon-designer-bollywood-fashion-style-saree-for-original-imahfb9bqfnwmugy.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/z/n/h/free-677-peach-maroon-designer-bollywood-fashion-style-saree-for-original-imahfb9bqfnwmugy.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Silk",
      Type: "Traditional Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Zari",
      Color: "Red, Gold",
      Occasion: "Wedding, Festive",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 15,
  },
  {
    name: "Embroidered Georgette Saree",
    description:
      "Georgette saree with delicate embroidery, ideal for formal gatherings and evening events.",
    price: 2999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/v/m/l/free-kanchipuram-kanjivaram-banarasi-high-quality-pure-handloom-original-imagrs6rddt68axt.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/v/m/l/free-kanchipuram-kanjivaram-banarasi-high-quality-pure-handloom-original-imagrs6rddt68axt.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/v/m/l/free-kanchipuram-kanjivaram-banarasi-high-quality-pure-handloom-original-imagrs6rddt68axt.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/v/m/l/free-kanchipuram-kanjivaram-banarasi-high-quality-pure-handloom-original-imagrs6rddt68axt.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Georgette",
      Type: "Embroidered Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Embroidered",
      Color: "Blue, Silver",
      Occasion: "Formal, Evening",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 20,
  },
  {
    name: "Kanjivaram Silk Saree",
    description:
      "Traditional Kanjivaram silk saree with rich border and pallu, perfect for South Indian weddings.",
    price: 7999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/5/u/f/free-3580s162aa-samah-unstitched-original-imahfvf6jhgk5hcv.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/5/u/f/free-3580s162aa-samah-unstitched-original-imahfvf6jhgk5hcv.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/5/u/f/free-3580s162aa-samah-unstitched-original-imahfvf6jhgk5hcv.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/d/t/g/free-3580s162aa-samah-unstitched-original-imahfvf6zupcwazm.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/d/t/g/free-3580s162aa-samah-unstitched-original-imahfvf6zupcwazm.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Kanjivaram Silk",
      Type: "Traditional Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Contrast Border",
      Color: "Green, Gold",
      Occasion: "Wedding, Bridal",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 12,
  },
  {
    name: "Printed Cotton Silk Saree",
    description:
      "Comfortable cotton silk saree with floral prints, suitable for casual and daily wear.",
    price: 1499,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/knrsjgw0/sari/p/r/o/free-pubg-varni-fashion-icon-unstitched-original-imag2dz9wdnnqebh.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/kjem3rk0-0/sari/w/g/t/free-01-leerovenita-unstitched-original-imafyzd6jm675hq5.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/kjem3rk0-0/sari/w/g/t/free-01-leerovenita-unstitched-original-imafyzd6jm675hq5.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/kjem3rk0-0/sari/w/g/t/free-01-leerovenita-unstitched-original-imafyzd6jm675hq5.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Cotton Silk",
      Type: "Printed Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Printed",
      Color: "Yellow, Pink",
      Occasion: "Casual, Daily Wear",
      "Fabric care": "Hand Wash",
    },
    stockQuantity: 25,
  },
  {
    name: "Chiffon Embellished Saree",
    description:
      "Chiffon saree with stone embellishments, perfect for parties and evening occasions.",
    price: 3999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/r/k/d/free-3577s337-samah-unstitched-original-imagysstgksb8egq.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/r/k/d/free-3577s337-samah-unstitched-original-imagysstgksb8egq.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Chiffon",
      Type: "Embellished Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Embellished",
      Color: "Black, Silver",
      Occasion: "Party, Evening",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 18,
  },
  {
    name: "Bhagalpuri Silk Saree",
    description:
      "Bhagalpuri silk saree with intricate prints, suitable for festive occasions and celebrations.",
    price: 2499,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/kirr24w0-0/sari/t/n/5/free-bahubali-orange-dharam-fabrics-unstitched-original-imafyhjgctab75n7.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/kirr24w0-0/sari/o/s/k/free-bahubali-orange-dharam-fabrics-unstitched-original-imafyhjgtbupuvts.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/kirr24w0-0/sari/o/s/k/free-bahubali-orange-dharam-fabrics-unstitched-original-imafyhjgtbupuvts.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/kirr24w0-0/sari/o/s/k/free-bahubali-orange-dharam-fabrics-unstitched-original-imafyhjgtbupuvts.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Bhagalpuri Silk",
      Type: "Printed Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Printed",
      Color: "Orange, Blue",
      Occasion: "Festive, Party",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 22,
  },
  {
    name: "Bandhani Cotton Saree",
    description:
      "Bandhani cotton saree with tie-and-dye patterns, ideal for traditional events and cultural gatherings.",
    price: 1899,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/k01b8280/sari/f/g/9/free-simple-sadi-semi-paithani-bengali-silk-velvet-pochampally-original-imafjx69bbtymzka.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/k01b8280/sari/f/g/9/free-simple-sadi-semi-paithani-bengali-silk-velvet-pochampally-original-imafjx69bbtymzka.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/k01b8280/sari/f/g/9/free-simple-sadi-semi-paithani-bengali-silk-velvet-pochampally-original-imafjx69bbtymzka.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/k01b8280/sari/f/g/9/free-simple-sadi-semi-paithani-bengali-silk-velvet-pochampally-original-imafjx69bbtymzka.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/k01b8280/sari/f/g/9/free-simple-sadi-semi-paithani-bengali-silk-velvet-pochampally-original-imafjx69bbtymzka.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/k01b8280/sari/f/g/9/free-simple-sadi-semi-paithani-bengali-silk-velvet-pochampally-original-imafjx69bbtymzka.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Cotton",
      Type: "Bandhani Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Bandhani",
      Color: "Pink, Yellow",
      Occasion: "Traditional, Cultural",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 20,
  },
  {
    name: "Tussar Silk Saree",
    description:
      "Tussar silk saree with golden motifs, perfect for formal gatherings and festive occasions.",
    price: 3499,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/3/u/6/free-classic-linen-digital-printed-with-tassel-and-bloouse-original-imagnpka9whea47k.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/3/u/6/free-classic-linen-digital-printed-with-tassel-and-bloouse-original-imagnpka9whea47k.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Tussar Silk",
      Type: "Embroidered Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Embroidered",
      Color: "Cream, Gold",
      Occasion: "Formal, Festive",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 16,
  },
  {
    name: "Printed Linen Saree",
    description:
      "Linen saree with printed motifs, ideal for casual wear and everyday outings.",
    price: 1699,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/7/z/q/free-dgp-white-grey-color-designer-saree-designer-blouse-original-imagyzyhsz3pydam.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/7/z/q/free-dgp-white-grey-color-designer-saree-designer-blouse-original-imagyzyhsz3pydam.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/7/z/q/free-dgp-white-grey-color-designer-saree-designer-blouse-original-imagyzyhsz3pydam.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/7/z/q/free-dgp-white-grey-color-designer-saree-designer-blouse-original-imagyzyhsz3pydam.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/7/z/q/free-dgp-white-grey-color-designer-saree-designer-blouse-original-imagyzyhsz3pydam.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/7/z/q/free-dgp-white-grey-color-designer-saree-designer-blouse-original-imagyzyhsz3pydam.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Linen",
      Type: "Printed Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Printed",
      Color: "White, Blue",
      Occasion: "Casual, Daily Wear",
      "Fabric care": "Hand Wash",
    },
    stockQuantity: 24,
  },
  {
    name: "Banarasi Silk Saree",
    description:
      "Banarasi silk saree with intricate weaving and golden zari work, perfect for weddings and grand celebrations.",
    price: 8999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/m/5/s/free-banarasi-handloom-golden-work-light-weight-stone-original-imagqbz34rgetfsz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/m/5/s/free-banarasi-handloom-golden-work-light-weight-stone-original-imagqbz34rgetfsz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/m/5/s/free-banarasi-handloom-golden-work-light-weight-stone-original-imagqbz34rgetfsz.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Banarasi Silk",
      Type: "Traditional Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Zari",
      Color: "Purple, Gold",
      Occasion: "Wedding, Bridal",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 10,
  },
  {
    name: "Kota Doria Silk Saree",
    description:
      "Lightweight Kota Doria silk saree with intricate thread work, perfect for summer weddings and daytime events.",
    price: 3799,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/0/h/4/free-ac-qr-84-prachi-looknchoice-unstitched-original-imahfczzanw6ypcw.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/0/h/4/free-ac-qr-84-prachi-looknchoice-unstitched-original-imahfczzanw6ypcw.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/0/h/4/free-ac-qr-84-prachi-looknchoice-unstitched-original-imahfczzanw6ypcw.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Kota Doria Silk",
      Type: "Thread Work Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Thread Work",
      Color: "Peach, Gold",
      Occasion: "Daytime Wedding, Summer",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 18,
  },
  {
    name: "Chanderi Cotton Saree",
    description:
      "Chanderi cotton saree with golden zari border, suitable for festive occasions and cultural celebrations.",
    price: 2599,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/n/d/n/free-pari-100-wedding-top-brand-banarasi-high-quality-pure-original-imahf3eye3tgayfm.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/n/d/n/free-pari-100-wedding-top-brand-banarasi-high-quality-pure-original-imahf3eye3tgayfm.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/n/d/n/free-pari-100-wedding-top-brand-banarasi-high-quality-pure-original-imahf3eye3tgayfm.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/n/d/n/free-pari-100-wedding-top-brand-banarasi-high-quality-pure-original-imahf3eye3tgayfm.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Chanderi Cotton",
      Type: "Zari Border Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Zari Border",
      Color: "Pink, Silver",
      Occasion: "Festive, Cultural",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 16,
  },
  {
    name: "Kalamkari Cotton Saree",
    description:
      "Kalamkari cotton saree with hand-painted motifs, ideal for artistic events and traditional gatherings.",
    price: 2999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/f/y/m/free-1061-almaari-fashion-unstitched-original-imahf7yen4hyth8h.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/f/y/m/free-1061-almaari-fashion-unstitched-original-imahf7yen4hyth8h.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/f/y/m/free-1061-almaari-fashion-unstitched-original-imahf7yen4hyth8h.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/f/y/m/free-1061-almaari-fashion-unstitched-original-imahf7yen4hyth8h.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Kalamkari Cotton",
      Type: "Hand-painted Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Hand-painted",
      Color: "Multi-color",
      Occasion: "Artistic, Traditional",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 20,
  },
  {
    name: "Embroidered Tussar Silk Saree",
    description:
      "Tussar silk saree with intricate embroidery, perfect for formal events and evening parties.",
    price: 4299,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/kmmcrrk0/sari/g/4/l/free-chikuoorakeri-silk-saree-pure-cotton-sarees-for-summer-original-imagfhgyzcnupyab.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/kmmcrrk0/sari/g/4/l/free-chikuoorakeri-silk-saree-pure-cotton-sarees-for-summer-original-imagfhgyzcnupyab.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/kmmcrrk0/sari/g/4/l/free-chikuoorakeri-silk-saree-pure-cotton-sarees-for-summer-original-imagfhgyzcnupyab.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/kmmcrrk0/sari/g/4/l/free-chikuoorakeri-silk-saree-pure-cotton-sarees-for-summer-original-imagfhgyzcnupyab.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Tussar Silk",
      Type: "Embroidered Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Embroidered",
      Color: "Beige, Gold",
      Occasion: "Formal, Evening",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 14,
  },
  {
    name: "Bollywood Style Saree",
    description:
      "Designer Bollywood-style saree with sequin and mirror work, ideal for glamorous events and red carpet occasions.",
    price: 6599,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/r/k/d/free-3577s337-samah-unstitched-original-imagysstgksb8egq.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/r/k/d/free-3577s337-samah-unstitched-original-imagysstgksb8egq.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Georgette",
      Type: "Designer Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Sequin and Mirror Work",
      Color: "Silver, Black",
      Occasion: "Glamorous Events, Red Carpet",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 12,
  },
  {
    name: "Handloom Khadi Saree",
    description:
      "Handloom khadi saree with minimalist design, suitable for eco-friendly fashion enthusiasts and cultural events.",
    price: 1999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/w/j/y/free-1061-almaari-fashion-unstitched-original-imahfcfxvshykae7.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/w/j/y/free-1061-almaari-fashion-unstitched-original-imahfcfxvshykae7.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/w/j/y/free-1061-almaari-fashion-unstitched-original-imahfcfxvshykae7.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/w/j/y/free-1061-almaari-fashion-unstitched-original-imahfcfxvshykae7.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/3/r/g/free-suhali-b-bella-creation-unstitched-original-imahfjcf3grcfcqh.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Handloom Khadi",
      Type: "Minimalist Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Plain",
      Color: "Off-White",
      Occasion: "Cultural, Eco-friendly",
      "Fabric care": "Hand Wash",
    },
    stockQuantity: 22,
  },
  {
    name: "Mysore Silk Saree",
    description:
      "Classic Mysore silk saree with traditional motifs and golden zari, perfect for South Indian weddings and festive celebrations.",
    price: 7499,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/e/0/w/free-rekha6-the-private-lable-unstitched-original-imahfck5yegpjaes.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/e/0/w/free-rekha6-the-private-lable-unstitched-original-imahfck5yegpjaes.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/e/0/w/free-rekha6-the-private-lable-unstitched-original-imahfck5yegpjaes.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/e/0/w/free-rekha6-the-private-lable-unstitched-original-imahfck5yegpjaes.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/e/0/w/free-rekha6-the-private-lable-unstitched-original-imahfck5yegpjaes.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/e/0/w/free-rekha6-the-private-lable-unstitched-original-imahfck5yegpjaes.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/e/0/w/free-rekha6-the-private-lable-unstitched-original-imahfck5yegpjaes.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Mysore Silk",
      Type: "Traditional Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Zari",
      Color: "Royal Blue, Gold",
      Occasion: "Wedding, Festive",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 8,
  },
  {
    name: "Printed Silk Crepe Saree",
    description:
      "Silk crepe saree with digital prints, ideal for modern fashionistas and chic evening events.",
    price: 3199,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/n/g/i/free-turky-a-v-m-print-unstitched-original-imahyftu9eqxamsz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/n/g/i/free-turky-a-v-m-print-unstitched-original-imahyftu9eqxamsz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/n/g/i/free-turky-a-v-m-print-unstitched-original-imahyftu9eqxamsz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/n/g/i/free-turky-a-v-m-print-unstitched-original-imahyftu9eqxamsz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/n/g/i/free-turky-a-v-m-print-unstitched-original-imahyftu9eqxamsz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/n/g/i/free-turky-a-v-m-print-unstitched-original-imahyftu9eqxamsz.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/n/g/i/free-turky-a-v-m-print-unstitched-original-imahyftu9eqxamsz.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Silk Crepe",
      Type: "Printed Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Digital Prints",
      Color: "Green, Pink",
      Occasion: "Modern, Evening",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 18,
  },
  {
    name: "Linen Jamdani Saree",
    description:
      "Linen jamdani saree with intricate jamdani weaving, perfect for summer weddings and cultural gatherings.",
    price: 4399,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/z/h/j/free-3702s152r-satrani-unstitched-original-imahfxmkbwfdudha.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/z/h/j/free-3702s152r-satrani-unstitched-original-imahfxmkbwfdudha.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/z/h/j/free-3702s152r-satrani-unstitched-original-imahfxmkbwfdudha.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/f/w/i/free-3702s152r-satrani-unstitched-original-imahfxmkvxyfafyx.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/s/a/f/free-3702s152r-satrani-unstitched-original-imahfxmkfdnh8zg4.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Linen",
      Type: "Jamdani Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Jamdani Weave",
      Color: "White, Gold",
      Occasion: "Summer Wedding, Cultural",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 14,
  },
  {
    name: "Kashmiri Embroidered Saree",
    description:
      "Kashmiri embroidered saree with intricate Kashmiri embroidery, suitable for traditional events and winter festivities.",
    price: 4999,
    images: [
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/v/f/9/free-suhali-b-bella-creation-unstitched-original-imahfjcfyhgcedw3.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/v/f/9/free-suhali-b-bella-creation-unstitched-original-imahfjcfyhgcedw3.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/v/f/9/free-suhali-b-bella-creation-unstitched-original-imahfjcfyhgcedw3.jpeg?q=70&crop=false",
      "https://rukminim2.flixcart.com/image/1080/1080/xif0q/sari/h/y/i/free-suhali-b-bella-creation-unstitched-original-imahfjcfjjzku2cy.jpeg?q=70&crop=false",
    ],
    attributes: {
      Fabric: "Georgette",
      Type: "Embroidered Saree",
      "Sales Package": "Saree with Blouse Piece",
      Pattern: "Kashmiri Embroidery",
      Color: "Red, Gold",
      Occasion: "Traditional, Winter Festive",
      "Fabric care": "Dry Clean Only",
    },
    stockQuantity: 16,
  },
];

export default sareeData;
